name: Publish package to GitHub Packages
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Publish package
        run: mvn clean --batch-mode deploy -s ../conf/settings.xml \
        -Dgithub.username=${{ secrets.PACKAGES_USER }} \
        -Dgithub.token=${{ secrets.PACKAGES_TOKEN }}